language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install: 
  - "pip install ."
  - "pip install pytest-cov"
  - "pip install codecov"
  - travis_wait 30 mvn install
# command to run tests
script: py.test --cov=./
# codecov
after_success:
  - codecov --token f98efc8d-1618-4942-87d6-c11337ae3840